# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/turbot

    goos:
      - linux

    goarch:
      - amd64

    id: "steampipe"
    binary: "{{ .ProjectName }}.plugin"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_ {{ .Os }}_{{ .Arch }}"
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
